language: generic
before_deploy:
  pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync $TRAVIS_BUILD_DIR s3://nypl-static-qa --region=us-east-1 --delete --acl public-read --exclude ".git/*" --exclude ".*"
  skip_cleanup: true
  on:
    branch: initial
